apiVersion: v2
name: demo-app
description: A Helm chart for deploying demo application on Kubernetes
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - demo
  - microservices
  - nodejs
maintainers:
  - name: Jatin Songara
    email: jatin.songara@outlook.com
